; SPDX-License-Identifier: AGPL-3.0-or-later

[openai]
base_url = http://localhost:8080/api
api_key = sk-xxxxxxxxxxxxxxxxxxxxxxx
model_name = medgemma-1.5:4b

[analysis]
knowledge_base_ids = yyyyyyyyyyyyyyyyyyyyyyy

[prompts]
prompt = Please, begin by extracting the medical data from the following text and converting it into a FHIR compliant JSON resource bundle. After that, verify whether the operators have adhered to any of the attached protocols. If you cannot find any protocol or the attached protocols are not relevant to the specific case, please search for suitable protocols on the Web.
# prompt = Please, begin by translating the text from Italian to English. After that, extract the medical data from the translated text and convert it into a FHIR compliant JSON resource bundle. Finally, verify whether the operators have adhered to any of the attached protocols.  If you cannot find any protocol or the attached protocols are not relevant to the specific case, please search for suitable protocols on the Web.
# prompt = Please, begin by translating the text from French to English. After that, extract the medical data from the translated text and convert it into a FHIR compliant JSON resource bundle. Finally, verify whether the operators have adhered to any of the attached protocols. If you cannot find any protocol or the attached protocols are not relevant to the specific case, please search for suitable protocols on the Web.
# prompt = Please, begin by translating the text from Hebrew to English. After that, extract the medical data from the translated text and convert it into a FHIR compliant JSON resource bundle. Finally, verify whether the operators have adhered to any of the attached protocols. If you cannot find any protocol or the attached protocols are not relevant to the specific case, please search for suitable protocols on the Web.
temp_prompt = Please, verify whether the operators have adhered to any of the attached protocols. If you cannot find any protocol or the attached protocols are not relevant to the specific case, please search for suitable protocols on the Web.
# prompt = Please, begin by summarizing the presentation on sepsis in emergency surgery contained in the following text. After that, please tell me what you think about it and if there are specific points requiring further discussion.
# prompt = Please, begin by summarizing the presentation on surgical equity contained in the following text. After that, please tell me what you think about it and if there are specific points requiring further discussion.
[triggers]
start = Start recording
stop = Stop recording
temp_check = Check now
# start = Comincia a registrare
# stop = Termina di registrare
# temp_check = Controlla adesso
# start = Commence à enregistrer
# stop = Termine à enregistrer
# temp_check = Vérifier maintenant
# start = התחל להקליט
# stop = הפסק להקליט
# temp_check = בדוק עכשיו
[tts]
